---
version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_REPLICA_FETCH_MAX_BYTES: 1000000000
      KAFKA_PRODUCER_MAX_REQUEST_SIZE: 1000000000
      KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES: 1000000000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-webiview:
    image: sourcelaborg/kafka-webview:latest
    depends_on:
      - kafka
    volumes:
      - ./kafkawebview_data:/app/data
    ports:
      - "8090:8080"
